# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaymentCondition")

model_instance <- PaymentCondition$new()

test_that("discount_days", {
  # tests for the property `discount_days` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`discount_days`, "EXPECTED_RESULT")
})

test_that("discount_percentage", {
  # tests for the property `discount_percentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`discount_percentage`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("payment_term_days", {
  # tests for the property `payment_term_days` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`payment_term_days`, "EXPECTED_RESULT")
})
