# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SupplierInvoiceCreate")

model_instance <- SupplierInvoiceCreate$new()

test_that("currency", {
  # tests for the property `currency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("goodsReceiptId", {
  # tests for the property `goodsReceiptId` (character)
  # References the goods receipt entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`goodsReceiptId`, "EXPECTED_RESULT")
})

test_that("invoiceDate", {
  # tests for the property `invoiceDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`invoiceDate`, "EXPECTED_RESULT")
})

test_that("invoiceNumber", {
  # tests for the property `invoiceNumber` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`invoiceNumber`, "EXPECTED_RESULT")
})

test_that("lineItems", {
  # tests for the property `lineItems` (AnyType)
  # JSON array of &#x60;{product_id, name, quantity, unitPriceNet, taxRate}&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`lineItems`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("purchaseOrderId", {
  # tests for the property `purchaseOrderId` (character)
  # References the purchase order entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`purchaseOrderId`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (SupplierInvoiceStatus)
  # One of: draft | matched | has_variances | posted | cancelled

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("supplierContactId", {
  # tests for the property `supplierContactId` (character)
  # References the supplier entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`supplierContactId`, "EXPECTED_RESULT")
})

test_that("supplierName", {
  # tests for the property `supplierName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`supplierName`, "EXPECTED_RESULT")
})

test_that("totalGrossAmount", {
  # tests for the property `totalGrossAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalGrossAmount`, "EXPECTED_RESULT")
})

test_that("totalNetAmount", {
  # tests for the property `totalNetAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalNetAmount`, "EXPECTED_RESULT")
})
