# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EventSubscription")

model_instance <- EventSubscription$new()

test_that("callback_url", {
  # tests for the property `callback_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`callback_url`, "EXPECTED_RESULT")
})

test_that("event_type", {
  # tests for the property `event_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_type`, "EXPECTED_RESULT")
})

test_that("is_active", {
  # tests for the property `is_active` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_active`, "EXPECTED_RESULT")
})

test_that("subscription_id", {
  # tests for the property `subscription_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`subscription_id`, "EXPECTED_RESULT")
})
