# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ConfigFieldInfo")

model_instance <- ConfigFieldInfo$new()

test_that("kind", {
  # tests for the property `kind` (ConfigFieldKind)

  # uncomment below to test the property
  #expect_equal(model.instance$`kind`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("placeholder", {
  # tests for the property `placeholder` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`placeholder`, "EXPECTED_RESULT")
})

test_that("required", {
  # tests for the property `required` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`required`, "EXPECTED_RESULT")
})
