# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PayrollSummary")

model_instance <- PayrollSummary$new()

test_that("firstName", {
  # tests for the property `firstName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`firstName`, "EXPECTED_RESULT")
})

test_that("hourlyGross", {
  # tests for the property `hourlyGross` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hourlyGross`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("jobTitle", {
  # tests for the property `jobTitle` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`jobTitle`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

test_that("monthlySalary", {
  # tests for the property `monthlySalary` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`monthlySalary`, "EXPECTED_RESULT")
})

test_that("months", {
  # tests for the property `months` (array[PayrollMonth])

  # uncomment below to test the property
  #expect_equal(model.instance$`months`, "EXPECTED_RESULT")
})

test_that("weeklyHours", {
  # tests for the property `weeklyHours` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`weeklyHours`, "EXPECTED_RESULT")
})

test_that("year", {
  # tests for the property `year` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`year`, "EXPECTED_RESULT")
})
