# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PlausibilityApi")

api_instance <- PlausibilityApi$new()

test_that("PlausibilityCheckApi", {
  # tests for PlausibilityCheckApi
  # base path: https://demo.simplebilly.com
  # @param date_from character  (optional)
  # @param date_to character  (optional)
  # @return [PlausibilityReport]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
