# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnlageEksApi")

api_instance <- AnlageEksApi$new()

test_that("EksApi", {
  # tests for EksApi
  # base path: https://demo.simplebilly.com
  # @param year integer 
  # @return [EksErgebnis]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
