# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UsageSnapshot")

model_instance <- UsageSnapshot$new()

test_that("connectors", {
  # tests for the property `connectors` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`connectors`, "EXPECTED_RESULT")
})

test_that("invoicesThisMonth", {
  # tests for the property `invoicesThisMonth` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`invoicesThisMonth`, "EXPECTED_RESULT")
})

test_that("overageSeats", {
  # tests for the property `overageSeats` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`overageSeats`, "EXPECTED_RESULT")
})

test_that("users", {
  # tests for the property `users` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`users`, "EXPECTED_RESULT")
})
