# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DatevImportRow")

model_instance <- DatevImportRow$new()

test_that("account", {
  # tests for the property `account` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`account`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("base_amount", {
  # tests for the property `base_amount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_amount`, "EXPECTED_RESULT")
})

test_that("base_currency", {
  # tests for the property `base_currency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`base_currency`, "EXPECTED_RESULT")
})

test_that("booking_text", {
  # tests for the property `booking_text` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`booking_text`, "EXPECTED_RESULT")
})

test_that("bu_key", {
  # tests for the property `bu_key` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bu_key`, "EXPECTED_RESULT")
})

test_that("cost_center1", {
  # tests for the property `cost_center1` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cost_center1`, "EXPECTED_RESULT")
})

test_that("cost_center2", {
  # tests for the property `cost_center2` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cost_center2`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("debit_credit", {
  # tests for the property `debit_credit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`debit_credit`, "EXPECTED_RESULT")
})

test_that("discount", {
  # tests for the property `discount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`discount`, "EXPECTED_RESULT")
})

test_that("document_date", {
  # tests for the property `document_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`document_date`, "EXPECTED_RESULT")
})

test_that("document_field2", {
  # tests for the property `document_field2` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`document_field2`, "EXPECTED_RESULT")
})

test_that("document_number", {
  # tests for the property `document_number` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`document_number`, "EXPECTED_RESULT")
})

test_that("eu_country_vat_id", {
  # tests for the property `eu_country_vat_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eu_country_vat_id`, "EXPECTED_RESULT")
})

test_that("eu_tax_rate", {
  # tests for the property `eu_tax_rate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eu_tax_rate`, "EXPECTED_RESULT")
})

test_that("exchange_rate", {
  # tests for the property `exchange_rate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`exchange_rate`, "EXPECTED_RESULT")
})

test_that("opposite_account", {
  # tests for the property `opposite_account` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`opposite_account`, "EXPECTED_RESULT")
})
