# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PeppolApi")

api_instance <- PeppolApi$new()

test_that("PeppolApi", {
  # tests for PeppolApi
  # base path: https://demo.simplebilly.com
  # @param id character 
  # @return [PeppolResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
