# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SupportTicket")

model_instance <- SupportTicket$new()

test_that("assignedTo", {
  # tests for the property `assignedTo` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assignedTo`, "EXPECTED_RESULT")
})

test_that("channelId", {
  # tests for the property `channelId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`channelId`, "EXPECTED_RESULT")
})

test_that("channelType", {
  # tests for the property `channelType` (SupportChannelType)

  # uncomment below to test the property
  #expect_equal(model.instance$`channelType`, "EXPECTED_RESULT")
})

test_that("closedAt", {
  # tests for the property `closedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`closedAt`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("customerEmail", {
  # tests for the property `customerEmail` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`customerEmail`, "EXPECTED_RESULT")
})

test_that("customerId", {
  # tests for the property `customerId` (character)
  # References the customer entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`customerId`, "EXPECTED_RESULT")
})

test_that("customerName", {
  # tests for the property `customerName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`customerName`, "EXPECTED_RESULT")
})

test_that("externalId", {
  # tests for the property `externalId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`externalId`, "EXPECTED_RESULT")
})

test_that("firstMessageAt", {
  # tests for the property `firstMessageAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`firstMessageAt`, "EXPECTED_RESULT")
})

test_that("lastMessageAt", {
  # tests for the property `lastMessageAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastMessageAt`, "EXPECTED_RESULT")
})

test_that("leadId", {
  # tests for the property `leadId` (character)
  # References the lead entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`leadId`, "EXPECTED_RESULT")
})

test_that("messageCount", {
  # tests for the property `messageCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`messageCount`, "EXPECTED_RESULT")
})

test_that("orderRef", {
  # tests for the property `orderRef` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`orderRef`, "EXPECTED_RESULT")
})

test_that("priority", {
  # tests for the property `priority` (TicketPriority)

  # uncomment below to test the property
  #expect_equal(model.instance$`priority`, "EXPECTED_RESULT")
})

test_that("resolution", {
  # tests for the property `resolution` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resolution`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (SupportTicketStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("subject", {
  # tests for the property `subject` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`subject`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
