# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SupportChannelApi")

api_instance <- SupportChannelApi$new()

test_that("CreateChannelApi", {
  # tests for CreateChannelApi
  # base path: https://demo.simplebilly.com
  # @param create_channel_dto CreateChannelDto 
  # @return [SupportChannel]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteChannelApi", {
  # tests for DeleteChannelApi
  # base path: https://demo.simplebilly.com
  # @param channel_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListChannelsApi", {
  # tests for ListChannelsApi
  # base path: https://demo.simplebilly.com
  # @return [array[SupportChannel]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateChannelApi", {
  # tests for UpdateChannelApi
  # base path: https://demo.simplebilly.com
  # @param channel_id character 
  # @param update_channel_dto UpdateChannelDto 
  # @return [SupportChannel]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
