# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EventSubscriptionApi")

api_instance <- EventSubscriptionApi$new()

test_that("CreateEventSubscription", {
  # tests for CreateEventSubscription
  # base path: https://demo.simplebilly.com
  # @param body AnyType 
  # @return [EventSubscription]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteEventSubscription", {
  # tests for DeleteEventSubscription
  # base path: https://demo.simplebilly.com
  # @param subscription_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListEventSubscriptions", {
  # tests for ListEventSubscriptions
  # base path: https://demo.simplebilly.com
  # @return [array[EventSubscription]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
