# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test KonzernBeteiligung")

model_instance <- KonzernBeteiligung$new()

test_that("company_name", {
  # tests for the property `company_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`company_name`, "EXPECTED_RESULT")
})

test_that("control_basis", {
  # tests for the property `control_basis` (array[character])
  # Erfüllte Kontroll-Indikatoren (§ 290 Abs. 2 HGB) als deutsche Bezeichnungen.

  # uncomment below to test the property
  #expect_equal(model.instance$`control_basis`, "EXPECTED_RESULT")
})

test_that("controlled", {
  # tests for the property `controlled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`controlled`, "EXPECTED_RESULT")
})

test_that("ownership_pct", {
  # tests for the property `ownership_pct` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ownership_pct`, "EXPECTED_RESULT")
})
