# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QuotaOverrideFeatures")

model_instance <- QuotaOverrideFeatures$new()

test_that("erp", {
  # tests for the property `erp` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`erp`, "EXPECTED_RESULT")
})

test_that("fancy_reports", {
  # tests for the property `fancy_reports` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fancy_reports`, "EXPECTED_RESULT")
})

test_that("tax_automations", {
  # tests for the property `tax_automations` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_automations`, "EXPECTED_RESULT")
})
