# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ShipmentApi")

api_instance <- ShipmentApi$new()

test_that("CreateShipment", {
  # tests for CreateShipment
  # base path: https://demo.simplebilly.com
  # @param shipment Shipment 
  # @return [Shipment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateShipmentFromOrder", {
  # tests for CreateShipmentFromOrder
  # base path: https://demo.simplebilly.com
  # Create a real shipment for an order: calls the configured carrier&#39;s label API, stores the returned tracking/label on a new shipment row, and marks the order as shipped.
  # @param order_number character 
  # @param create_shipment_request CreateShipmentRequest 
  # @return [Shipment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteShipment", {
  # tests for DeleteShipment
  # base path: https://demo.simplebilly.com
  # @param shipment_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetShipment", {
  # tests for GetShipment
  # base path: https://demo.simplebilly.com
  # @param shipment_id character 
  # @return [Shipment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListShipments", {
  # tests for ListShipments
  # base path: https://demo.simplebilly.com
  # @param page integer  (optional)
  # @param page_size integer  (optional)
  # @param search character  (optional)
  # @param include_deleted character Soft-delete entities: set true to include rows with `deleted_at` set. (optional)
  # @return [array[Shipment]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TrackOrderPublic", {
  # tests for TrackOrderPublic
  # base path: https://demo.simplebilly.com
  # Customer-facing tracking lookup: order number + email → shipment status and live carrier events. No auth (public storefront API).
  # @param track_order_request TrackOrderRequest 
  # @return [TrackOrderResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("TrackShipmentApi", {
  # tests for TrackShipmentApi
  # base path: https://demo.simplebilly.com
  # @param shipment_id character 
  # @return [TrackingInfo]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateShipmentStatus", {
  # tests for UpdateShipmentStatus
  # base path: https://demo.simplebilly.com
  # @param shipment_id character 
  # @param shipment_status_update ShipmentStatusUpdate 
  # @return [Shipment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
