# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ShipmentStatusUpdate")

model_instance <- ShipmentStatusUpdate$new()

test_that("delivered_at", {
  # tests for the property `delivered_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`delivered_at`, "EXPECTED_RESULT")
})

test_that("signed_by", {
  # tests for the property `signed_by` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`signed_by`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("tracking_number", {
  # tests for the property `tracking_number` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tracking_number`, "EXPECTED_RESULT")
})
