# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Package")

model_instance <- Package$new()

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("height_cm", {
  # tests for the property `height_cm` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`height_cm`, "EXPECTED_RESULT")
})

test_that("length_cm", {
  # tests for the property `length_cm` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`length_cm`, "EXPECTED_RESULT")
})

test_that("reference", {
  # tests for the property `reference` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reference`, "EXPECTED_RESULT")
})

test_that("weight_kg", {
  # tests for the property `weight_kg` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`weight_kg`, "EXPECTED_RESULT")
})

test_that("width_cm", {
  # tests for the property `width_cm` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`width_cm`, "EXPECTED_RESULT")
})
