# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Budget")

model_instance <- Budget$new()

test_that("category", {
  # tests for the property `category` (character)
  # Posting category key (matches &#x60;category&#x60; on journal entries).

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("monthlyGoal", {
  # tests for the property `monthlyGoal` (character)
  # Monthly goal amount (gross). 0 means \&quot;no goal set\&quot;.

  # uncomment below to test the property
  #expect_equal(model.instance$`monthlyGoal`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})

test_that("year", {
  # tests for the property `year` (integer)
  # Budget year the goal applies to.

  # uncomment below to test the property
  #expect_equal(model.instance$`year`, "EXPECTED_RESULT")
})
