# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GezReport")

model_instance <- GezReport$new()

test_that("beitragsfreie_kfz", {
  # tests for the property `beitragsfreie_kfz` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`beitragsfreie_kfz`, "EXPECTED_RESULT")
})

test_that("beitragspflichtige_kfz", {
  # tests for the property `beitragspflichtige_kfz` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`beitragspflichtige_kfz`, "EXPECTED_RESULT")
})

test_that("betriebsstaetten", {
  # tests for the property `betriebsstaetten` (array[BetriebsstaettenDetail])

  # uncomment below to test the property
  #expect_equal(model.instance$`betriebsstaetten`, "EXPECTED_RESULT")
})

test_that("hinweis", {
  # tests for the property `hinweis` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hinweis`, "EXPECTED_RESULT")
})

test_that("hotelzimmer_beitrag", {
  # tests for the property `hotelzimmer_beitrag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hotelzimmer_beitrag`, "EXPECTED_RESULT")
})

test_that("jaehrlicher_beitrag", {
  # tests for the property `jaehrlicher_beitrag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`jaehrlicher_beitrag`, "EXPECTED_RESULT")
})

test_that("jahr", {
  # tests for the property `jahr` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`jahr`, "EXPECTED_RESULT")
})

test_that("kfz_beitrag", {
  # tests for the property `kfz_beitrag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`kfz_beitrag`, "EXPECTED_RESULT")
})

test_that("monatlicher_beitrag", {
  # tests for the property `monatlicher_beitrag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`monatlicher_beitrag`, "EXPECTED_RESULT")
})

test_that("vierteljaehrlicher_beitrag", {
  # tests for the property `vierteljaehrlicher_beitrag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vierteljaehrlicher_beitrag`, "EXPECTED_RESULT")
})
