# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CustomerInfo")

model_instance <- CustomerInfo$new()

test_that("annual_volume", {
  # tests for the property `annual_volume` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`annual_volume`, "EXPECTED_RESULT")
})

test_that("is_registered", {
  # tests for the property `is_registered` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_registered`, "EXPECTED_RESULT")
})
