# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StockTransferStatusUpdate")

model_instance <- StockTransferStatusUpdate$new()

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})
