# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BoxFit")

model_instance <- BoxFit$new()

test_that("height_cm", {
  # tests for the property `height_cm` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`height_cm`, "EXPECTED_RESULT")
})

test_that("item_count", {
  # tests for the property `item_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`item_count`, "EXPECTED_RESULT")
})

test_that("length_cm", {
  # tests for the property `length_cm` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`length_cm`, "EXPECTED_RESULT")
})

test_that("volume_cm3", {
  # tests for the property `volume_cm3` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`volume_cm3`, "EXPECTED_RESULT")
})

test_that("width_cm", {
  # tests for the property `width_cm` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`width_cm`, "EXPECTED_RESULT")
})
