# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ExpenseItem")

model_instance <- ExpenseItem$new()

test_that("amount", {
  # tests for the property `amount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("percentage", {
  # tests for the property `percentage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`percentage`, "EXPECTED_RESULT")
})
