# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DeclarationCreate")

model_instance <- DeclarationCreate$new()

test_that("declarationType", {
  # tests for the property `declarationType` (DeclarationType)
  # Art der Erklärung: \&quot;dcgk\&quot; (Entsprechenserklärung § 161 AktG) oder \&quot;unternehmensfuehrung\&quot; (Erklärung zur Unternehmensführung § 289f HGB).

  # uncomment below to test the property
  #expect_equal(model.instance$`declarationType`, "EXPECTED_RESULT")
})

test_that("isCurrent", {
  # tests for the property `isCurrent` (character)
  # Kennzeichnet die aktuell gültige Fassung (max. eine je Mandant).

  # uncomment below to test the property
  #expect_equal(model.instance$`isCurrent`, "EXPECTED_RESULT")
})

test_that("text", {
  # tests for the property `text` (character)
  # Inhalt der Erklärung als Markdown.

  # uncomment below to test the property
  #expect_equal(model.instance$`text`, "EXPECTED_RESULT")
})

test_that("validFrom", {
  # tests for the property `validFrom` (character)
  # Datum, ab dem die Erklärung gilt.

  # uncomment below to test the property
  #expect_equal(model.instance$`validFrom`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)
  # Versionsbezeichnung der Erklärung (z.B. \&quot;2025-01\&quot;).

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})
