# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Quotation")

model_instance <- Quotation$new()

test_that("address", {
  # tests for the property `address` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("contactId", {
  # tests for the property `contactId` (character)
  # References the contact entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`contactId`, "EXPECTED_RESULT")
})

test_that("contactName", {
  # tests for the property `contactName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contactName`, "EXPECTED_RESULT")
})

test_that("currency", {
  # tests for the property `currency` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currency`, "EXPECTED_RESULT")
})

test_that("expirationDate", {
  # tests for the property `expirationDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`expirationDate`, "EXPECTED_RESULT")
})

test_that("files", {
  # tests for the property `files` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`files`, "EXPECTED_RESULT")
})

test_that("introduction", {
  # tests for the property `introduction` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`introduction`, "EXPECTED_RESULT")
})

test_that("lineItems", {
  # tests for the property `lineItems` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`lineItems`, "EXPECTED_RESULT")
})

test_that("precedingSalesVoucherId", {
  # tests for the property `precedingSalesVoucherId` (character)
  # References the preceding sales voucher entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`precedingSalesVoucherId`, "EXPECTED_RESULT")
})

test_that("precedingSalesVoucherType", {
  # tests for the property `precedingSalesVoucherType` (PrecedingSalesVoucherType)

  # uncomment below to test the property
  #expect_equal(model.instance$`precedingSalesVoucherType`, "EXPECTED_RESULT")
})

test_that("quotationNumber", {
  # tests for the property `quotationNumber` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`quotationNumber`, "EXPECTED_RESULT")
})

test_that("remark", {
  # tests for the property `remark` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`remark`, "EXPECTED_RESULT")
})

test_that("subtotal", {
  # tests for the property `subtotal` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`subtotal`, "EXPECTED_RESULT")
})

test_that("taxCondition", {
  # tests for the property `taxCondition` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxCondition`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("totalAmount", {
  # tests for the property `totalAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalAmount`, "EXPECTED_RESULT")
})

test_that("totalTax", {
  # tests for the property `totalTax` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalTax`, "EXPECTED_RESULT")
})

test_that("voucherDate", {
  # tests for the property `voucherDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`voucherDate`, "EXPECTED_RESULT")
})

test_that("voucherStatus", {
  # tests for the property `voucherStatus` (VoucherStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`voucherStatus`, "EXPECTED_RESULT")
})
