# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InvoiceMatchRequest")

model_instance <- InvoiceMatchRequest$new()

test_that("supplier_invoice_id", {
  # tests for the property `supplier_invoice_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`supplier_invoice_id`, "EXPECTED_RESULT")
})
