# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PostingCategoryApi")

api_instance <- PostingCategoryApi$new()

test_that("CreatePostingCategory", {
  # tests for CreatePostingCategory
  # base path: https://demo.simplebilly.com
  # @param body AnyType 
  # @return [PostingCategory]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeletePostingCategory", {
  # tests for DeletePostingCategory
  # base path: https://demo.simplebilly.com
  # @param category_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListPostingCategories", {
  # tests for ListPostingCategories
  # base path: https://demo.simplebilly.com
  # @return [array[PostingCategory]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SeedPostingCategories", {
  # tests for SeedPostingCategories
  # base path: https://demo.simplebilly.com
  # @param skr_version character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdatePostingCategory", {
  # tests for UpdatePostingCategory
  # base path: https://demo.simplebilly.com
  # @param category_id character 
  # @param body AnyType 
  # @return [PostingCategory]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
