# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DpaStatus")

model_instance <- DpaStatus$new()

test_that("accepted", {
  # tests for the property `accepted` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accepted`, "EXPECTED_RESULT")
})

test_that("acceptedAt", {
  # tests for the property `acceptedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`acceptedAt`, "EXPECTED_RESULT")
})

test_that("acceptedBy", {
  # tests for the property `acceptedBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`acceptedBy`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})
