# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Coupon")

model_instance <- Coupon$new()

test_that("code", {
  # tests for the property `code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("discountType", {
  # tests for the property `discountType` (DiscountType)

  # uncomment below to test the property
  #expect_equal(model.instance$`discountType`, "EXPECTED_RESULT")
})

test_that("discountValue", {
  # tests for the property `discountValue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`discountValue`, "EXPECTED_RESULT")
})

test_that("expiresAt", {
  # tests for the property `expiresAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`expiresAt`, "EXPECTED_RESULT")
})

test_that("isActive", {
  # tests for the property `isActive` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isActive`, "EXPECTED_RESULT")
})

test_that("isCombineable", {
  # tests for the property `isCombineable` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isCombineable`, "EXPECTED_RESULT")
})

test_that("maxDiscountAmount", {
  # tests for the property `maxDiscountAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxDiscountAmount`, "EXPECTED_RESULT")
})

test_that("maxUses", {
  # tests for the property `maxUses` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxUses`, "EXPECTED_RESULT")
})

test_that("maxUsesPerCustomer", {
  # tests for the property `maxUsesPerCustomer` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxUsesPerCustomer`, "EXPECTED_RESULT")
})

test_that("minOrderAmount", {
  # tests for the property `minOrderAmount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`minOrderAmount`, "EXPECTED_RESULT")
})

test_that("productIds", {
  # tests for the property `productIds` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`productIds`, "EXPECTED_RESULT")
})

test_that("startsAt", {
  # tests for the property `startsAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`startsAt`, "EXPECTED_RESULT")
})
