# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TimeEntryClockOut")

model_instance <- TimeEntryClockOut$new()

test_that("clock_out", {
  # tests for the property `clock_out` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`clock_out`, "EXPECTED_RESULT")
})

test_that("hours", {
  # tests for the property `hours` (character)
  # Optional manual hours; when absent, derived from clock_in..clock_out.

  # uncomment below to test the property
  #expect_equal(model.instance$`hours`, "EXPECTED_RESULT")
})
