# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Workflow")

model_instance <- Workflow$new()

test_that("actions", {
  # tests for the property `actions` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`actions`, "EXPECTED_RESULT")
})

test_that("enabled", {
  # tests for the property `enabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`enabled`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("triggerEvent", {
  # tests for the property `triggerEvent` (character)
  # Event that triggers the workflow, e.g. &#x60;order.paid&#x60;, &#x60;order.shipped&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`triggerEvent`, "EXPECTED_RESULT")
})
