# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AdminApi")

api_instance <- AdminApi$new()

test_that("TriggerMirror", {
  # tests for TriggerMirror
  # base path: https://demo.simplebilly.com
  # @return [MirrorTriggerResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
