# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ContactApi")

api_instance <- ContactApi$new()

test_that("ContactSchema", {
  # tests for ContactSchema
  # base path: https://demo.simplebilly.com
  # Serve JSON Schema for client-side validation
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ContactTimeline", {
  # tests for ContactTimeline
  # base path: https://demo.simplebilly.com
  # Get the full per-contact timeline (Xentral §4.6/4.7).
  # Aggregates communications, quotations, orders, invoices and uploaded documents for a contact, merged into a single reverse-chronological feed.
  # @param contact_id character 
  # @return [ContactTimelineResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("CreateContact", {
  # tests for CreateContact
  # base path: https://demo.simplebilly.com
  # Create contact
  # @param body AnyType 
  # @return [Contact]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteContact", {
  # tests for DeleteContact
  # base path: https://demo.simplebilly.com
  # Soft-delete contact
  # @param contact_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetContact", {
  # tests for GetContact
  # base path: https://demo.simplebilly.com
  # Get single contact
  # @param contact_id character 
  # @return [Contact]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListContacts", {
  # tests for ListContacts
  # base path: https://demo.simplebilly.com
  # List contacts with search, type filter, and pagination
  # @param page integer  (optional)
  # @param page_size integer  (optional)
  # @param search character  (optional)
  # @param contact_type character  (optional)
  # @param tag character  (optional)
  # @return [array[Contact]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SalesVolume", {
  # tests for SalesVolume
  # base path: https://demo.simplebilly.com
  # Sales volume per contact
  # @param page integer  (optional)
  # @param page_size integer  (optional)
  # @param search character  (optional)
  # @param contact_type character  (optional)
  # @param tag character  (optional)
  # @return [SalesVolumeReport]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateContact", {
  # tests for UpdateContact
  # base path: https://demo.simplebilly.com
  # Update contact
  # @param contact_id character 
  # @param body AnyType 
  # @return [Contact]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
