# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InstituteProfile")

model_instance <- InstituteProfile$new()

test_that("instituteType", {
  # tests for the property `instituteType` (InstituteType)
  # Institutsart: \&quot;kein\&quot; | \&quot;kreditinstitut\&quot; | \&quot;finanzdienstleistungsinstitut\&quot; | \&quot;finanzunternehmen\&quot; | \&quot;versicherung\&quot;.

  # uncomment below to test the property
  #expect_equal(model.instance$`instituteType`, "EXPECTED_RESULT")
})

test_that("kapitalmarktorientiert", {
  # tests for the property `kapitalmarktorientiert` (character)
  # Kapitalmarktorientierung (§ 325 Abs. 4 HGB): Offenlegungsfrist 4 statt 12 Monate.

  # uncomment below to test the property
  #expect_equal(model.instance$`kapitalmarktorientiert`, "EXPECTED_RESULT")
})
