# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StockTransfer")

model_instance <- StockTransfer$new()

test_that("lineItems", {
  # tests for the property `lineItems` (AnyType)
  # JSON array of &#x60;{product_id, name, quantity, batch_number?}&#x60;.

  # uncomment below to test the property
  #expect_equal(model.instance$`lineItems`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("sourceWarehouseId", {
  # tests for the property `sourceWarehouseId` (character)
  # References the warehouse entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`sourceWarehouseId`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (StockTransferStatus)
  # One of: draft | completed | cancelled

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("targetWarehouseId", {
  # tests for the property `targetWarehouseId` (character)
  # References the warehouse entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`targetWarehouseId`, "EXPECTED_RESULT")
})

test_that("transferDate", {
  # tests for the property `transferDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`transferDate`, "EXPECTED_RESULT")
})

test_that("transferNumber", {
  # tests for the property `transferNumber` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`transferNumber`, "EXPECTED_RESULT")
})
