# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicDeliveryAppointmentStatusResponse")

model_instance <- PublicDeliveryAppointmentStatusResponse$new()

test_that("appointmentId", {
  # tests for the property `appointmentId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`appointmentId`, "EXPECTED_RESULT")
})

test_that("requestedDate", {
  # tests for the property `requestedDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`requestedDate`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("timeSlot", {
  # tests for the property `timeSlot` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`timeSlot`, "EXPECTED_RESULT")
})

test_that("warehouseName", {
  # tests for the property `warehouseName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`warehouseName`, "EXPECTED_RESULT")
})
