# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ReorderProposalLine")

model_instance <- ReorderProposalLine$new()

test_that("currentStock", {
  # tests for the property `currentStock` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`currentStock`, "EXPECTED_RESULT")
})

test_that("maxStock", {
  # tests for the property `maxStock` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxStock`, "EXPECTED_RESULT")
})

test_that("minStock", {
  # tests for the property `minStock` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`minStock`, "EXPECTED_RESULT")
})

test_that("productId", {
  # tests for the property `productId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`productId`, "EXPECTED_RESULT")
})

test_that("productName", {
  # tests for the property `productName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`productName`, "EXPECTED_RESULT")
})

test_that("reorderQuantity", {
  # tests for the property `reorderQuantity` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`reorderQuantity`, "EXPECTED_RESULT")
})

test_that("sku", {
  # tests for the property `sku` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sku`, "EXPECTED_RESULT")
})

test_that("suggestedQuantity", {
  # tests for the property `suggestedQuantity` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`suggestedQuantity`, "EXPECTED_RESULT")
})
