# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StilleReport")

model_instance <- StilleReport$new()

test_that("jahresueberschuss", {
  # tests for the property `jahresueberschuss` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`jahresueberschuss`, "EXPECTED_RESULT")
})

test_that("partners", {
  # tests for the property `partners` (array[StillePartnerZeile])

  # uncomment below to test the property
  #expect_equal(model.instance$`partners`, "EXPECTED_RESULT")
})

test_that("year", {
  # tests for the property `year` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`year`, "EXPECTED_RESULT")
})
