# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicDeliveryAppointmentResponse")

model_instance <- PublicDeliveryAppointmentResponse$new()

test_that("appointmentId", {
  # tests for the property `appointmentId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`appointmentId`, "EXPECTED_RESULT")
})

test_that("confirmationHint", {
  # tests for the property `confirmationHint` (character)
  # Carries the status-check token (email is out of scope for now).

  # uncomment below to test the property
  #expect_equal(model.instance$`confirmationHint`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})
