# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Plan")

model_instance <- Plan$new()

test_that("features", {
  # tests for the property `features` (PlanFeatures)

  # uncomment below to test the property
  #expect_equal(model.instance$`features`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("limits", {
  # tests for the property `limits` (PlanLimits)

  # uncomment below to test the property
  #expect_equal(model.instance$`limits`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("priceEur", {
  # tests for the property `priceEur` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`priceEur`, "EXPECTED_RESULT")
})
