# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PayrollSummaryItem")

model_instance <- PayrollSummaryItem$new()

test_that("employee_count", {
  # tests for the property `employee_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`employee_count`, "EXPECTED_RESULT")
})

test_that("month", {
  # tests for the property `month` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`month`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (PayrollRunStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("total_employer_cost", {
  # tests for the property `total_employer_cost` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_employer_cost`, "EXPECTED_RESULT")
})

test_that("total_gross", {
  # tests for the property `total_gross` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_gross`, "EXPECTED_RESULT")
})

test_that("total_net", {
  # tests for the property `total_net` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_net`, "EXPECTED_RESULT")
})

test_that("year", {
  # tests for the property `year` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`year`, "EXPECTED_RESULT")
})
