# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UpdateSubscriptionRequest")

model_instance <- UpdateSubscriptionRequest$new()

test_that("event_type", {
  # tests for the property `event_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`event_type`, "EXPECTED_RESULT")
})

test_that("is_active", {
  # tests for the property `is_active` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_active`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("secret", {
  # tests for the property `secret` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`secret`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})
