# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TrainingAssignment")

model_instance <- TrainingAssignment$new()

test_that("assignedBy", {
  # tests for the property `assignedBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assignedBy`, "EXPECTED_RESULT")
})

test_that("createdAt", {
  # tests for the property `createdAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdAt`, "EXPECTED_RESULT")
})

test_that("deletedAt", {
  # tests for the property `deletedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`deletedAt`, "EXPECTED_RESULT")
})

test_that("dueDate", {
  # tests for the property `dueDate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dueDate`, "EXPECTED_RESULT")
})

test_that("employeeId", {
  # tests for the property `employeeId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`employeeId`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (AssignmentStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("tenantId", {
  # tests for the property `tenantId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tenantId`, "EXPECTED_RESULT")
})

test_that("trainingId", {
  # tests for the property `trainingId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`trainingId`, "EXPECTED_RESULT")
})

test_that("updatedAt", {
  # tests for the property `updatedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedAt`, "EXPECTED_RESULT")
})
