# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GobdExportApi")

api_instance <- GobdExportApi$new()

test_that("BuchhalterCsvApi", {
  # tests for BuchhalterCsvApi
  # base path: https://demo.simplebilly.com
  # @param date_from character 
  # @param date_to character 
  # @return [GoBDExportResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GobdExportApi", {
  # tests for GobdExportApi
  # base path: https://demo.simplebilly.com
  # GoBD/GDPdU export. Default: ZIP archive (&#x60;index.xml&#x60; + CSV tables, IDEA format). &#x60;?format&#x3D;csv&#x60; returns the legacy single-journal CSV as JSON.
  # @param year integer 
  # @param format character Export format: `zip` (default, full GDPdU/IDEA export) or `csv` (legacy single-journal CSV as JSON). (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
