# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test KonzernStatus")

model_instance <- KonzernStatus$new()

test_that("groessenbefreit", {
  # tests for the property `groessenbefreit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`groessenbefreit`, "EXPECTED_RESULT")
})

test_that("kapitalmarktorientiert", {
  # tests for the property `kapitalmarktorientiert` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`kapitalmarktorientiert`, "EXPECTED_RESULT")
})

test_that("konzernabschlusspflicht", {
  # tests for the property `konzernabschlusspflicht` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`konzernabschlusspflicht`, "EXPECTED_RESULT")
})

test_that("missing_group_figures", {
  # tests for the property `missing_group_figures` (character)
  # Keine group_figures-Zeile für das Jahr vorhanden → keine Größenbefreiung.

  # uncomment below to test the property
  #expect_equal(model.instance$`missing_group_figures`, "EXPECTED_RESULT")
})

test_that("mutterunternehmen", {
  # tests for the property `mutterunternehmen` (character)
  # Mutterunternehmen: mindestens eine beherrschte Beteiligung (§ 290 Abs. 1 HGB).

  # uncomment below to test the property
  #expect_equal(model.instance$`mutterunternehmen`, "EXPECTED_RESULT")
})

test_that("parent_name", {
  # tests for the property `parent_name` (character)
  # Mutterunternehmen für die Zwischenholding-Befreiung (§ 291 HGB).

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_name`, "EXPECTED_RESULT")
})

test_that("parent_situs", {
  # tests for the property `parent_situs` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_situs`, "EXPECTED_RESULT")
})

test_that("participations", {
  # tests for the property `participations` (array[KonzernBeteiligung])

  # uncomment below to test the property
  #expect_equal(model.instance$`participations`, "EXPECTED_RESULT")
})

test_that("thresholds", {
  # tests for the property `thresholds` (KonzernThresholds)

  # uncomment below to test the property
  #expect_equal(model.instance$`thresholds`, "EXPECTED_RESULT")
})

test_that("year", {
  # tests for the property `year` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`year`, "EXPECTED_RESULT")
})

test_that("zwischenholding_befreit", {
  # tests for the property `zwischenholding_befreit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`zwischenholding_befreit`, "EXPECTED_RESULT")
})

test_that("zwischenholding_hinweis", {
  # tests for the property `zwischenholding_hinweis` (character)
  # Hinweis zu den § 291-Voraussetzungen (EU/EWR-Sitz, geprüfter Konzernabschluss).

  # uncomment below to test the property
  #expect_equal(model.instance$`zwischenholding_hinweis`, "EXPECTED_RESULT")
})
