# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RecurringTemplateApi")

api_instance <- RecurringTemplateApi$new()

test_that("CreateRecurringTemplate", {
  # tests for CreateRecurringTemplate
  # base path: https://demo.simplebilly.com
  # @param body AnyType 
  # @return [RecurringTemplate]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRecurringTemplate", {
  # tests for DeleteRecurringTemplate
  # base path: https://demo.simplebilly.com
  # @param template_id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRecurringTemplate", {
  # tests for GetRecurringTemplate
  # base path: https://demo.simplebilly.com
  # @param template_id character 
  # @return [RecurringTemplate]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListRecurringTemplates", {
  # tests for ListRecurringTemplates
  # base path: https://demo.simplebilly.com
  # @return [array[RecurringTemplate]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
