# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateConnectionRequest")

model_instance <- CreateConnectionRequest$new()

test_that("api_key", {
  # tests for the property `api_key` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_key`, "EXPECTED_RESULT")
})

test_that("api_secret", {
  # tests for the property `api_secret` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`api_secret`, "EXPECTED_RESULT")
})

test_that("config", {
  # tests for the property `config` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`config`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("platform", {
  # tests for the property `platform` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`platform`, "EXPECTED_RESULT")
})

test_that("shop_domain", {
  # tests for the property `shop_domain` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shop_domain`, "EXPECTED_RESULT")
})
