# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GenerateVariantsRequest")

model_instance <- GenerateVariantsRequest$new()

test_that("options", {
  # tests for the property `options` (map(array[character]))
  # Option name → list of values, e.g. &#x60;{\&quot;Color\&quot;: [\&quot;Red\&quot;, \&quot;Blue\&quot;], \&quot;Size\&quot;: [\&quot;S\&quot;, \&quot;M\&quot;]}&#x60;. The cartesian product of these lists is generated.

  # uncomment below to test the property
  #expect_equal(model.instance$`options`, "EXPECTED_RESULT")
})

test_that("priceDelta", {
  # tests for the property `priceDelta` (character)
  # Optional per-variant price delta applied to every generated variant.

  # uncomment below to test the property
  #expect_equal(model.instance$`priceDelta`, "EXPECTED_RESULT")
})

test_that("productId", {
  # tests for the property `productId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`productId`, "EXPECTED_RESULT")
})

test_that("skuPrefix", {
  # tests for the property `skuPrefix` (character)
  # Optional prefix for the generated SKUs (suffix is the option values joined by &#x60;-&#x60;). Falls back to the parent product&#39;s SKU.

  # uncomment below to test the property
  #expect_equal(model.instance$`skuPrefix`, "EXPECTED_RESULT")
})
