# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaymentApi")

api_instance <- PaymentApi$new()

test_that("CreatePayment", {
  # tests for CreatePayment
  # base path: https://demo.simplebilly.com
  # @param payment_create PaymentCreate 
  # @return [Payment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeletePayment", {
  # tests for DeletePayment
  # base path: https://demo.simplebilly.com
  # @param id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPayment", {
  # tests for GetPayment
  # base path: https://demo.simplebilly.com
  # @param id character 
  # @return [Payment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetPayments", {
  # tests for GetPayments
  # base path: https://demo.simplebilly.com
  # @param page integer  (optional)
  # @param page_size integer  (optional)
  # @param search character  (optional)
  # @param include_deleted character Soft-delete entities: set true to include rows with `deleted_at` set. (optional)
  # @return [array[Payment]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PaymentRestore", {
  # tests for PaymentRestore
  # base path: https://demo.simplebilly.com
  # @param id character 
  # @return [Payment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdatePayment", {
  # tests for UpdatePayment
  # base path: https://demo.simplebilly.com
  # @param id character 
  # @param body AnyType 
  # @return [Payment]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
