# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ReturnLogisticsSummary")

model_instance <- ReturnLogisticsSummary$new()

test_that("byStatus", {
  # tests for the property `byStatus` (AnyType)
  # Number of return orders per status.

  # uncomment below to test the property
  #expect_equal(model.instance$`byStatus`, "EXPECTED_RESULT")
})

test_that("byWarehouse", {
  # tests for the property `byWarehouse` (array[ReturnWarehouseSummary])
  # Per-warehouse aggregation.

  # uncomment below to test the property
  #expect_equal(model.instance$`byWarehouse`, "EXPECTED_RESULT")
})

test_that("itemsRestocked", {
  # tests for the property `itemsRestocked` (integer)
  # Sum of &#x60;restock: true&#x60; line-item quantities.

  # uncomment below to test the property
  #expect_equal(model.instance$`itemsRestocked`, "EXPECTED_RESULT")
})

test_that("itemsScrapped", {
  # tests for the property `itemsScrapped` (integer)
  # Sum of &#x60;restock: false&#x60; line-item quantities (scrapped/disposed).

  # uncomment below to test the property
  #expect_equal(model.instance$`itemsScrapped`, "EXPECTED_RESULT")
})

test_that("totalItems", {
  # tests for the property `totalItems` (integer)
  # Sum of all line-item quantities across returns.

  # uncomment below to test the property
  #expect_equal(model.instance$`totalItems`, "EXPECTED_RESULT")
})

test_that("totalReturns", {
  # tests for the property `totalReturns` (integer)
  # Total number of return orders (excluding soft-deleted).

  # uncomment below to test the property
  #expect_equal(model.instance$`totalReturns`, "EXPECTED_RESULT")
})
