# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PublicReturnRequest")

model_instance <- PublicReturnRequest$new()

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("items", {
  # tests for the property `items` (array[PublicReturnItem])

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("orderNumber", {
  # tests for the property `orderNumber` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`orderNumber`, "EXPECTED_RESULT")
})
