# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SepaDirectDebitResponse")

model_instance <- SepaDirectDebitResponse$new()

test_that("content_type", {
  # tests for the property `content_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`content_type`, "EXPECTED_RESULT")
})

test_that("filename", {
  # tests for the property `filename` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`filename`, "EXPECTED_RESULT")
})

test_that("xml_content", {
  # tests for the property `xml_content` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`xml_content`, "EXPECTED_RESULT")
})
