# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TrainingsApi")

api_instance <- TrainingsApi$new()

test_that("GetMyTrainings", {
  # tests for GetMyTrainings
  # base path: https://demo.simplebilly.com
  # @return [array[MyTrainingItem]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTrainingContent", {
  # tests for GetTrainingContent
  # base path: https://demo.simplebilly.com
  # @param code character Training code, e.g. data_privacy
  # @return [TrainingContent]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetTrainingOverview", {
  # tests for GetTrainingOverview
  # base path: https://demo.simplebilly.com
  # @return [array[HrTrainingOverview]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SubmitTrainingResult", {
  # tests for SubmitTrainingResult
  # base path: https://demo.simplebilly.com
  # @param submit_result_dto SubmitResultDto 
  # @return [SubmitResultResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
