# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InstituteCheckItem")

model_instance <- InstituteCheckItem$new()

test_that("exists", {
  # tests for the property `exists` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`exists`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})
