# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CartItemInput")

model_instance <- CartItemInput$new()

test_that("product_id", {
  # tests for the property `product_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`product_id`, "EXPECTED_RESULT")
})

test_that("quantity", {
  # tests for the property `quantity` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`quantity`, "EXPECTED_RESULT")
})
