# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BWARevenue")

model_instance <- BWARevenue$new()

test_that("revenue_breakdown", {
  # tests for the property `revenue_breakdown` (array[RevenueItem])

  # uncomment below to test the property
  #expect_equal(model.instance$`revenue_breakdown`, "EXPECTED_RESULT")
})

test_that("total_revenue", {
  # tests for the property `total_revenue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_revenue`, "EXPECTED_RESULT")
})
