# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PaygapApi")

api_instance <- PaygapApi$new()

test_that("PaygapAuskunftApi", {
  # tests for PaygapAuskunftApi
  # base path: https://demo.simplebilly.com
  # @param employee_id character 
  # @return [PayGapInfoResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PaygapExportApi", {
  # tests for PaygapExportApi
  # base path: https://demo.simplebilly.com
  # @return [PayGapExportResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PaygapReportApi", {
  # tests for PaygapReportApi
  # base path: https://demo.simplebilly.com
  # @return [PayGapReport]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
