# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BookkeepingApi")

api_instance <- BookkeepingApi$new()

test_that("AllocatePaymentApi", {
  # tests for AllocatePaymentApi
  # base path: https://demo.simplebilly.com
  # Allocate a payment to an invoice
  # @param allocate_payment_request AllocatePaymentRequest 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("BwaReportApi", {
  # tests for BwaReportApi
  # base path: https://demo.simplebilly.com
  # Get BWA (Betriebswirtschaftliche Auswertung) report
  # @param year integer  (optional)
  # @param month integer  (optional)
  # @return [BWAReport]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ElsterStatusApi", {
  # tests for ElsterStatusApi
  # base path: https://demo.simplebilly.com
  # @return [ElsterStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ElsterValidateApi", {
  # tests for ElsterValidateApi
  # base path: https://demo.simplebilly.com
  # @param zeitraum character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ElsterXmlApi", {
  # tests for ElsterXmlApi
  # base path: https://demo.simplebilly.com
  # @param zeitraum character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetCashflow", {
  # tests for GetCashflow
  # base path: https://demo.simplebilly.com
  # GET /api/v1/bookkeeping/cashflow Returns operating, investing, and financing cashflow for the given period.
  # @param year integer  (optional)
  # @param month integer  (optional)
  # @return [CashflowReport]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetLiquidity", {
  # tests for GetLiquidity
  # base path: https://demo.simplebilly.com
  # GET /api/v1/bookkeeping/liquidity Returns current liquidity position with ratios.
  # @return [LiquidityPosition]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOpenInvoicesApi", {
  # tests for GetOpenInvoicesApi
  # base path: https://demo.simplebilly.com
  # Get open invoices for a customer
  # @param customer_id character 
  # @return [array[Invoice]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetVerfahrensdokumentation", {
  # tests for GetVerfahrensdokumentation
  # base path: https://demo.simplebilly.com
  # GET /api/v1/bookkeeping/verfahrensdokumentation Returns the complete compliance catalog of all documented modules.
  # @return [Verfahrensdokumentation]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RunDunningApi", {
  # tests for RunDunningApi
  # base path: https://demo.simplebilly.com
  # @return [DunningResult]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
