# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ChangelogEntry")

model_instance <- ChangelogEntry$new()

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})
