# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PackingQueueItem")

model_instance <- PackingQueueItem$new()

test_that("created_at", {
  # tests for the property `created_at` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_at`, "EXPECTED_RESULT")
})

test_that("customer_id", {
  # tests for the property `customer_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`customer_id`, "EXPECTED_RESULT")
})

test_that("delivery_note_printed", {
  # tests for the property `delivery_note_printed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`delivery_note_printed`, "EXPECTED_RESULT")
})

test_that("items", {
  # tests for the property `items` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("items_count", {
  # tests for the property `items_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`items_count`, "EXPECTED_RESULT")
})

test_that("label_printed", {
  # tests for the property `label_printed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label_printed`, "EXPECTED_RESULT")
})

test_that("order_number", {
  # tests for the property `order_number` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`order_number`, "EXPECTED_RESULT")
})

test_that("order_status", {
  # tests for the property `order_status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`order_status`, "EXPECTED_RESULT")
})

test_that("shipment_id", {
  # tests for the property `shipment_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shipment_id`, "EXPECTED_RESULT")
})

test_that("shipping_address", {
  # tests for the property `shipping_address` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`shipping_address`, "EXPECTED_RESULT")
})

test_that("shipping_method", {
  # tests for the property `shipping_method` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`shipping_method`, "EXPECTED_RESULT")
})

test_that("tracking_number", {
  # tests for the property `tracking_number` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tracking_number`, "EXPECTED_RESULT")
})

test_that("video_recording", {
  # tests for the property `video_recording` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`video_recording`, "EXPECTED_RESULT")
})
