# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ShippingThresholdUpdate")

model_instance <- ShippingThresholdUpdate$new()

test_that("isActive", {
  # tests for the property `isActive` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isActive`, "EXPECTED_RESULT")
})

test_that("maxSellable", {
  # tests for the property `maxSellable` (integer)
  # Optional ceiling for the deliverable quantity.

  # uncomment below to test the property
  #expect_equal(model.instance$`maxSellable`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("productId", {
  # tests for the property `productId` (character)
  # None &#x3D; applies to all products. References the product entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`productId`, "EXPECTED_RESULT")
})

test_that("reserveStock", {
  # tests for the property `reserveStock` (integer)
  # Buffer of stock that must not be sold.

  # uncomment below to test the property
  #expect_equal(model.instance$`reserveStock`, "EXPECTED_RESULT")
})

test_that("warehouseId", {
  # tests for the property `warehouseId` (character)
  # None &#x3D; applies to all warehouses. References the warehouse entity.

  # uncomment below to test the property
  #expect_equal(model.instance$`warehouseId`, "EXPECTED_RESULT")
})
