# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TrackingInfo")

model_instance <- TrackingInfo$new()

test_that("carrier", {
  # tests for the property `carrier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`carrier`, "EXPECTED_RESULT")
})

test_that("estimated_delivery", {
  # tests for the property `estimated_delivery` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`estimated_delivery`, "EXPECTED_RESULT")
})

test_that("events", {
  # tests for the property `events` (array[TrackingEvent])

  # uncomment below to test the property
  #expect_equal(model.instance$`events`, "EXPECTED_RESULT")
})

test_that("raw_response", {
  # tests for the property `raw_response` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`raw_response`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("tracking_number", {
  # tests for the property `tracking_number` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tracking_number`, "EXPECTED_RESULT")
})
