# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test FristenErgebnis")

model_instance <- FristenErgebnis$new()

test_that("anzahl", {
  # tests for the property `anzahl` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`anzahl`, "EXPECTED_RESULT")
})

test_that("fristen", {
  # tests for the property `fristen` (array[FristEintrag])

  # uncomment below to test the property
  #expect_equal(model.instance$`fristen`, "EXPECTED_RESULT")
})
