# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ApiResponseSubscriptionOverview")

model_instance <- ApiResponseSubscriptionOverview$new()

test_that("data", {
  # tests for the property `data` (ApiResponseSubscriptionOverviewData)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("error", {
  # tests for the property `error` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("success", {
  # tests for the property `success` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`success`, "EXPECTED_RESULT")
})
