# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ReplenishmentResponse")

model_instance <- ReplenishmentResponse$new()

test_that("generatedAt", {
  # tests for the property `generatedAt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`generatedAt`, "EXPECTED_RESULT")
})

test_that("lines", {
  # tests for the property `lines` (array[ReplenishmentSuggestionLine])

  # uncomment below to test the property
  #expect_equal(model.instance$`lines`, "EXPECTED_RESULT")
})

test_that("targetWarehouseId", {
  # tests for the property `targetWarehouseId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`targetWarehouseId`, "EXPECTED_RESULT")
})

test_that("totalSuggestedQuantity", {
  # tests for the property `totalSuggestedQuantity` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalSuggestedQuantity`, "EXPECTED_RESULT")
})
