# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test KstApi")

api_instance <- KstApi$new()

test_that("KstApi", {
  # tests for KstApi
  # base path: https://demo.simplebilly.com
  # @param year integer 
  # @param gewinn character  (optional)
  # @return [KstErgebnis]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
