# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TaxRateCreate")

model_instance <- TaxRateCreate$new()

test_that("countryCode", {
  # tests for the property `countryCode` (character)
  # ISO 3166-1 alpha-2 country code.

  # uncomment below to test the property
  #expect_equal(model.instance$`countryCode`, "EXPECTED_RESULT")
})

test_that("effectiveFrom", {
  # tests for the property `effectiveFrom` (character)
  # Date this rate took effect; &#x60;None&#x60; &#x3D; not date-bound.

  # uncomment below to test the property
  #expect_equal(model.instance$`effectiveFrom`, "EXPECTED_RESULT")
})

test_that("isDefault", {
  # tests for the property `isDefault` (character)
  # Default rate for the country (one per country); fallback for lookups when no dated rate applies.

  # uncomment below to test the property
  #expect_equal(model.instance$`isDefault`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Human name, e.g. \&quot;VAT\&quot;.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("ratePercent", {
  # tests for the property `ratePercent` (integer)
  # Rate in hundredths of a percent: 1900 &#x3D; 19.00%.

  # uncomment below to test the property
  #expect_equal(model.instance$`ratePercent`, "EXPECTED_RESULT")
})
