# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GdprApi")

api_instance <- GdprApi$new()

test_that("AcceptDpa", {
  # tests for AcceptDpa
  # base path: https://demo.simplebilly.com
  # Record DPA acceptance: sets dpa_accepted_at/by/version on the tenant settings row (created with company-type defaults if missing).
  # @param dpa_accept_request DpaAcceptRequest 
  # @return [DpaStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AccountErasure", {
  # tests for AccountErasure
  # base path: https://demo.simplebilly.com
  # Erase ALL personal data of the tenant (TOS §11: deletion 90 days after termination).
  # Anonymizes every contact, anonymizes personal fields on bookkeeping records (orders/invoices/payments keep amounts and dates for GoBD), removes the tenant linkage of the (global, saasy-framework) users and marks the erasure on &#x60;tenant_settings.gdpr_erased_at&#x60;. No row is physically deleted. The audit triggers on the touched tables record who/when.
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ErasureContact", {
  # tests for ErasureContact
  # base path: https://demo.simplebilly.com
  # Anonymize + soft-delete a contact: personal attributes are cleared, the record itself is kept for GoBD retention (Art. 17(3)(e) DSGVO). The audit trigger on &#x60;contacts&#x60; already records who/when.
  # @param contact_id character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExportContactData", {
  # tests for ExportContactData
  # base path: https://demo.simplebilly.com
  # Art. 15 data-subject access export for a contact.
  # Returns the contact itself plus the tenant-scoped rows linked to it.  ## Relations The &#x60;customers&#x60;/&#x60;orders&#x60;/&#x60;invoices&#x60;/&#x60;payments&#x60; tables have no FK to &#x60;contacts&#x60;; they are linked through the &#x60;customer_id&#x60; column, which per the app&#39;s conventions holds one of: - the admin customer&#39;s &#x60;customer_id&#x60; (a UUID, often the same value as   the contact&#39;s &#x60;contact_id&#x60;/&#x60;customer_number&#x60;), - the buyer&#39;s email for shop orders, or - the marketplace&#39;s external customer id for plugin orders.  The export therefore matches the contact&#39;s identifiers (&#x60;contact_id&#x60;, &#x60;customer_number&#x60;, &#x60;external_id&#x60;, &#x60;email&#x60;) plus any resolved customer ids against &#x60;customer_id&#x60;. &#x60;delivery_notes&#x60; and &#x60;customer_communications&#x60; reference contacts directly via &#x60;contact_id&#x60;. Soft-deleted rows are included (their data is still processed and retained for GoBD). Relations that genuinely do not exist for a contact stay empty but the key is always present.
  # @param contact_id character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ExportGdpr", {
  # tests for ExportGdpr
  # base path: https://demo.simplebilly.com
  # Export the current user&#39;s personal data (GDPR Art. 15/20).
  # No admin permission required: a user always exports their own data.
  # @return [ApiResponseGdprExport]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetDpa", {
  # tests for GetDpa
  # base path: https://demo.simplebilly.com
  # Current DPA acceptance status (from tenant_settings).
  # @return [DpaStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
