#' SimpleBilly API
#'
#' Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
#'
#' The version of the OpenAPI document: 0.1.0
#' Contact: support@simplebilly.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Lead operations
#' @description LeadApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  ListLeadsApi  ####################
#'
#' library(openapi)
#' var_status <- "status_example" # character |  (Optional)
#' var_source <- "source_example" # character |  (Optional)
#' var_search <- "search_example" # character |  (Optional)
#' var_page <- 56 # integer |  (Optional)
#' var_page_size <- 56 # integer |  (Optional)
#'
#' api_instance <- LeadApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListLeadsApi(status = var_status, source = var_source, search = var_search, page = var_page, page_size = var_page_sizedata_file = "result.txt")
#' result <- api_instance$ListLeadsApi(status = var_status, source = var_source, search = var_search, page = var_page, page_size = var_page_size)
#' dput(result)
#'
#'
#' ####################  UpdateLeadApi  ####################
#'
#' library(openapi)
#' var_lead_id <- "lead_id_example" # character | 
#' var_lead_update <- LeadUpdate$new("company_example", "convertedAt_example", "createdAt_example", "email_example", "firstContactAt_example", "name_example", "notes_example", "phone_example", 123, "source_example", LeadStatus$new(), TODO, "tenantId_example", "updatedAt_example") # LeadUpdate | 
#'
#' api_instance <- LeadApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$UpdateLeadApi(var_lead_id, var_lead_updatedata_file = "result.txt")
#' result <- api_instance$UpdateLeadApi(var_lead_id, var_lead_update)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
LeadApi <- R6::R6Class(
  "LeadApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new LeadApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' 
    #'
    #' @param status (optional) No description
    #' @param source (optional) No description
    #' @param search (optional) No description
    #' @param page (optional) No description
    #' @param page_size (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return array[Lead]
    ListLeadsApi = function(status = NULL, source = NULL, search = NULL, page = NULL, page_size = NULL, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListLeadsApiWithHttpInfo(status, source, search, page, page_size, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param status (optional) No description
    #' @param source (optional) No description
    #' @param search (optional) No description
    #' @param page (optional) No description
    #' @param page_size (optional) No description
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (array[Lead]) with additional information such as HTTP status code, headers
    ListLeadsApiWithHttpInfo = function(status = NULL, source = NULL, search = NULL, page = NULL, page_size = NULL, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE




      if (!is.null(`page`) && `page` <  0) {
        stop("Invalid value for `page` when calling LeadApi$ListLeadsApi, must be bigger than or equal to 0.")
      }

      if (!is.null(`page_size`) && `page_size` <  0) {
        stop("Invalid value for `page_size` when calling LeadApi$ListLeadsApi, must be bigger than or equal to 0.")
      }

      query_params[["status"]] <- `status`

      query_params[["source"]] <- `source`

      query_params[["search"]] <- `search`

      query_params[["page"]] <- `page`

      query_params[["page_size"]] <- `page_size`

      local_var_url_path <- "/api/v1/support/leads"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[Lead]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param lead_id 
    #' @param lead_update 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return Lead
    UpdateLeadApi = function(lead_id, lead_update, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$UpdateLeadApiWithHttpInfo(lead_id, lead_update, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param lead_id 
    #' @param lead_update 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (Lead) with additional information such as HTTP status code, headers
    UpdateLeadApiWithHttpInfo = function(lead_id, lead_update, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`lead_id`)) {
        stop("Missing required parameter `lead_id`.")
      }

      if (missing(`lead_update`)) {
        stop("Missing required parameter `lead_update`.")
      }

      if (!missing(`lead_id`) && is.null(`lead_id`)) {
        stop("Invalid value for `lead_id` when calling LeadApi$UpdateLeadApi, `lead_id` is not nullable")
      }

      if (!missing(`lead_update`) && is.null(`lead_update`)) {
        stop("Invalid value for `lead_update` when calling LeadApi$UpdateLeadApi, `lead_update` is not nullable")
      }

      if (!is.null(`lead_update`)) {
        local_var_body <- `lead_update`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/api/v1/support/leads/{lead_id}"
      if (!missing(`lead_id`)) {
        local_var_url_path <- gsub("\\{lead_id\\}", URLencode(as.character(`lead_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PUT",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "Lead"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
