#' SimpleBilly API
#'
#' Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
#'
#' The version of the OpenAPI document: 0.1.0
#' Contact: support@simplebilly.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title WarehouseStock operations
#' @description WarehouseStockApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  CreateWarehouseStock  ####################
#'
#' library(openapi)
#' var_warehouse_id <- "warehouse_id_example" # character | 
#' var_stock_adjustment <- StockAdjustment$new(123, "batchNumber_example", "binLocation_example", "expiryDate_example", "productId_example", c("serialNumbers_example")) # StockAdjustment | 
#'
#' api_instance <- WarehouseStockApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$CreateWarehouseStock(var_warehouse_id, var_stock_adjustmentdata_file = "result.txt")
#' result <- api_instance$CreateWarehouseStock(var_warehouse_id, var_stock_adjustment)
#' dput(result)
#'
#'
#' ####################  DeleteWarehouseStock  ####################
#'
#' library(openapi)
#' var_warehouse_id <- "warehouse_id_example" # character | 
#' var_product_id <- "product_id_example" # character | 
#'
#' api_instance <- WarehouseStockApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$DeleteWarehouseStock(var_warehouse_id, var_product_id)
#'
#'
#' ####################  ListWarehouseStock  ####################
#'
#' library(openapi)
#' var_warehouse_id <- "warehouse_id_example" # character | 
#'
#' api_instance <- WarehouseStockApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$ListWarehouseStock(var_warehouse_iddata_file = "result.txt")
#' result <- api_instance$ListWarehouseStock(var_warehouse_id)
#' dput(result)
#'
#'
#' ####################  UpdateWarehouseStock  ####################
#'
#' library(openapi)
#' var_warehouse_id <- "warehouse_id_example" # character | 
#' var_product_id <- "product_id_example" # character | 
#' var_stock_adjustment <- StockAdjustment$new(123, "batchNumber_example", "binLocation_example", "expiryDate_example", "productId_example", c("serialNumbers_example")) # StockAdjustment | 
#'
#' api_instance <- WarehouseStockApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$UpdateWarehouseStock(var_warehouse_id, var_product_id, var_stock_adjustmentdata_file = "result.txt")
#' result <- api_instance$UpdateWarehouseStock(var_warehouse_id, var_product_id, var_stock_adjustment)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
WarehouseStockApi <- R6::R6Class(
  "WarehouseStockApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new WarehouseStockApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param stock_adjustment 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return WarehouseStock
    CreateWarehouseStock = function(warehouse_id, stock_adjustment, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$CreateWarehouseStockWithHttpInfo(warehouse_id, stock_adjustment, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param stock_adjustment 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (WarehouseStock) with additional information such as HTTP status code, headers
    CreateWarehouseStockWithHttpInfo = function(warehouse_id, stock_adjustment, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`warehouse_id`)) {
        stop("Missing required parameter `warehouse_id`.")
      }

      if (missing(`stock_adjustment`)) {
        stop("Missing required parameter `stock_adjustment`.")
      }

      if (!missing(`warehouse_id`) && is.null(`warehouse_id`)) {
        stop("Invalid value for `warehouse_id` when calling WarehouseStockApi$CreateWarehouseStock, `warehouse_id` is not nullable")
      }

      if (!missing(`stock_adjustment`) && is.null(`stock_adjustment`)) {
        stop("Invalid value for `stock_adjustment` when calling WarehouseStockApi$CreateWarehouseStock, `stock_adjustment` is not nullable")
      }

      if (!is.null(`stock_adjustment`)) {
        local_var_body <- `stock_adjustment`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/api/v1/warehouses/{warehouse_id}/stock"
      if (!missing(`warehouse_id`)) {
        local_var_url_path <- gsub("\\{warehouse_id\\}", URLencode(as.character(`warehouse_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "WarehouseStock"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param product_id 
    #' @param ... Other optional arguments
    #'
    #' @return void
    DeleteWarehouseStock = function(warehouse_id, product_id, ...) {
      local_var_response <- self$DeleteWarehouseStockWithHttpInfo(warehouse_id, product_id, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param product_id 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    DeleteWarehouseStockWithHttpInfo = function(warehouse_id, product_id, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`warehouse_id`)) {
        stop("Missing required parameter `warehouse_id`.")
      }

      if (missing(`product_id`)) {
        stop("Missing required parameter `product_id`.")
      }

      if (!missing(`warehouse_id`) && is.null(`warehouse_id`)) {
        stop("Invalid value for `warehouse_id` when calling WarehouseStockApi$DeleteWarehouseStock, `warehouse_id` is not nullable")
      }

      if (!missing(`product_id`) && is.null(`product_id`)) {
        stop("Invalid value for `product_id` when calling WarehouseStockApi$DeleteWarehouseStock, `product_id` is not nullable")
      }

      local_var_url_path <- "/api/v1/warehouses/{warehouse_id}/stock/{product_id}"
      if (!missing(`warehouse_id`)) {
        local_var_url_path <- gsub("\\{warehouse_id\\}", URLencode(as.character(`warehouse_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`product_id`)) {
        local_var_url_path <- gsub("\\{product_id\\}", URLencode(as.character(`product_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "DELETE",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return array[WarehouseStock]
    ListWarehouseStock = function(warehouse_id, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$ListWarehouseStockWithHttpInfo(warehouse_id, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (array[WarehouseStock]) with additional information such as HTTP status code, headers
    ListWarehouseStockWithHttpInfo = function(warehouse_id, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`warehouse_id`)) {
        stop("Missing required parameter `warehouse_id`.")
      }

      if (!missing(`warehouse_id`) && is.null(`warehouse_id`)) {
        stop("Invalid value for `warehouse_id` when calling WarehouseStockApi$ListWarehouseStock, `warehouse_id` is not nullable")
      }

      local_var_url_path <- "/api/v1/warehouses/{warehouse_id}/stock"
      if (!missing(`warehouse_id`)) {
        local_var_url_path <- gsub("\\{warehouse_id\\}", URLencode(as.character(`warehouse_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "array[WarehouseStock]"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param product_id 
    #' @param stock_adjustment 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return WarehouseStock
    UpdateWarehouseStock = function(warehouse_id, product_id, stock_adjustment, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$UpdateWarehouseStockWithHttpInfo(warehouse_id, product_id, stock_adjustment, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param warehouse_id 
    #' @param product_id 
    #' @param stock_adjustment 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (WarehouseStock) with additional information such as HTTP status code, headers
    UpdateWarehouseStockWithHttpInfo = function(warehouse_id, product_id, stock_adjustment, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`warehouse_id`)) {
        stop("Missing required parameter `warehouse_id`.")
      }

      if (missing(`product_id`)) {
        stop("Missing required parameter `product_id`.")
      }

      if (missing(`stock_adjustment`)) {
        stop("Missing required parameter `stock_adjustment`.")
      }

      if (!missing(`warehouse_id`) && is.null(`warehouse_id`)) {
        stop("Invalid value for `warehouse_id` when calling WarehouseStockApi$UpdateWarehouseStock, `warehouse_id` is not nullable")
      }

      if (!missing(`product_id`) && is.null(`product_id`)) {
        stop("Invalid value for `product_id` when calling WarehouseStockApi$UpdateWarehouseStock, `product_id` is not nullable")
      }

      if (!missing(`stock_adjustment`) && is.null(`stock_adjustment`)) {
        stop("Invalid value for `stock_adjustment` when calling WarehouseStockApi$UpdateWarehouseStock, `stock_adjustment` is not nullable")
      }

      if (!is.null(`stock_adjustment`)) {
        local_var_body <- `stock_adjustment`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/api/v1/warehouses/{warehouse_id}/stock/{product_id}"
      if (!missing(`warehouse_id`)) {
        local_var_url_path <- gsub("\\{warehouse_id\\}", URLencode(as.character(`warehouse_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`product_id`)) {
        local_var_url_path <- gsub("\\{product_id\\}", URLencode(as.character(`product_id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "PUT",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "WarehouseStock"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
