#' SimpleBilly API
#'
#' Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
#'
#' The version of the OpenAPI document: 0.1.0
#' Contact: support@simplebilly.com
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Zugferd operations
#' @description ZugferdApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  GenerateZugferdApi  ####################
#'
#' library(openapi)
#' var_id <- "id_example" # character | 
#' var_supplier_name <- "supplier_name_example" # character |  (Optional)
#' var_supplier_street <- "supplier_street_example" # character |  (Optional)
#' var_supplier_city <- "supplier_city_example" # character |  (Optional)
#' var_supplier_zip <- "supplier_zip_example" # character |  (Optional)
#' var_supplier_country <- "supplier_country_example" # character |  (Optional)
#' var_supplier_vat_id <- "supplier_vat_id_example" # character |  (Optional)
#'
#' api_instance <- ZugferdApi$new()
#'
#' # Configure HTTP bearer authorization: bearer_token
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' api_instance$GenerateZugferdApi(var_id, supplier_name = var_supplier_name, supplier_street = var_supplier_street, supplier_city = var_supplier_city, supplier_zip = var_supplier_zip, supplier_country = var_supplier_country, supplier_vat_id = var_supplier_vat_id)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
ZugferdApi <- R6::R6Class(
  "ZugferdApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new ZugferdApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' 
    #'
    #' @param id 
    #' @param supplier_name (optional) No description
    #' @param supplier_street (optional) No description
    #' @param supplier_city (optional) No description
    #' @param supplier_zip (optional) No description
    #' @param supplier_country (optional) No description
    #' @param supplier_vat_id (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return void
    GenerateZugferdApi = function(id, supplier_name = NULL, supplier_street = NULL, supplier_city = NULL, supplier_zip = NULL, supplier_country = NULL, supplier_vat_id = NULL, ...) {
      local_var_response <- self$GenerateZugferdApiWithHttpInfo(id, supplier_name, supplier_street, supplier_city, supplier_zip, supplier_country, supplier_vat_id, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' 
    #'
    #' @param id 
    #' @param supplier_name (optional) No description
    #' @param supplier_street (optional) No description
    #' @param supplier_city (optional) No description
    #' @param supplier_zip (optional) No description
    #' @param supplier_country (optional) No description
    #' @param supplier_vat_id (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GenerateZugferdApiWithHttpInfo = function(id, supplier_name = NULL, supplier_street = NULL, supplier_city = NULL, supplier_zip = NULL, supplier_country = NULL, supplier_vat_id = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling ZugferdApi$GenerateZugferdApi, `id` is not nullable")
      }







      query_params[["supplier_name"]] <- `supplier_name`

      query_params[["supplier_street"]] <- `supplier_street`

      query_params[["supplier_city"]] <- `supplier_city`

      query_params[["supplier_zip"]] <- `supplier_zip`

      query_params[["supplier_country"]] <- `supplier_country`

      query_params[["supplier_vat_id"]] <- `supplier_vat_id`

      local_var_url_path <- "/api/v1/invoices/{id}/zugferd"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/pdf")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
